name: CI

on:
  push:
    tags:
    - v*
    branches:
    - main
    paths:
    - src/**
    - samples/**
    - tests/**
    - build/**
    - tools/**
    - .github/workflows/ci.yml
    - global.json
  pull_request:
    branches:
    - main
    paths:
    - src/**
    - samples/**
    - tests/**
    - build/**
    - tools/**
    - .github/workflows/ci.yml
    - global.json
  workflow_dispatch:

jobs:
  build:

    env:
      BUILD_CONFIG: 'ReleasePackages'
      SOLUTION: 'Legerity.Uno.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
